### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Ryuji-Ichikawa** [Ryuji-Ichikawa/protospace-35547#10]
※URL
https://protospace-35547.herokuapp.com/

**Comment by takumi0530** [comment]
@Ryuji-Ichikawa さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
トップページに遷移してしまいます。

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
コメント文面なしでユーザー名のみのものが投稿されてしまいます。

<img width="300" alt="スクリーンショット 2021-04-29 17 09 12" src="https://user-images.githubusercontent.com/76197191/116520402-a43c0d00-a90d-11eb-8889-09fb7a1042cd.png">


- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
ログアウト状態ですとログインページに遷移してしまい、確認できませんでした。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーの編集ページに遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Ryuji-Ichikawa** [comment]
いつもお世話になっております！
訂正箇所訂正し、動作確認いたしましたので、完了報告フォームも提出いたします。
お手数おかけしますが、よろしくお願いいたします。

**Comment by takumi0530** [comment]
@Ryuji-Ichikawa さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
